version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: postgres
    networks:
      - review-bot
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 2345:5432
  bot:
    image: node:14-alpine
    container_name: review-bot
    command: ['npm', 'run', 'start:dev']
    working_dir: /app
    env_file:
      - .env
    networks:
      - review-bot
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  review-bot:
    driver: bridge
